const menu = [
    {
        id: 1,
        title: 'Mouse Marca Logitech G203 RGB Lightsync, 6 botones, Dpi 8000, Alámbrico, Color blanco',
        category: 'mouse',
        priceOnline: 'S/ 154.00',
        priceNormal: 'S̶/̶ ̶1̶6̶6̶.̶0̶0̶',
        img: 'img/Productos/MouseGamer.png',
    },
    {
        id: 2,
        title: 'Audífono Bluetooth F9',
        category: 'headset',
        priceOnline: 'S/ 45.00',
        priceNormal: '̶S̶/̶ ̶5̶5̶.̶0̶0̶',
        img: 'img/Productos/F9.jpeg',
    },
    {
        id: 3,
        title: 'Audífono Bluetooth F9-5',
        category: 'headset',
        priceOnline: 'S/ 49.00',
        priceNormal: '̶S̶/̶ ̶5̶9̶.̶0̶0̶',
        img: 'img/Productos/F9-5.jpeg',
    },
    {
        id: 4,
        title: 'Audífono Bluetooth M-25',
        category: 'headset',
        priceOnline: 'S/ 89.00',
        priceNormal: '̶S̶/̶ ̶9̶9̶.̶0̶0̶',
        img: 'img/Productos/M-25.jpeg',
    },
    {
        id: 5,
        title: 'Audífono Bluetooth M-41',
        category: 'headset',
        priceOnline: 'S/ 79.00',
        priceNormal: '̶S̶/̶ ̶8̶9̶.̶0̶0̶',
        img: 'img/Productos/M-41.jpeg',
    },
    {
        id: 6,
        title: 'Audífono Bluetooth Pro6',
        category: 'headset',
        priceOnline: 'S/ 45.00',
        priceNormal: '̶S̶/̶ ̶5̶5̶.̶0̶0̶',
        img: 'img/Productos/Pro6.jpeg',
    },
    {
        id: 7,
        title: 'Audífono Bluetooth S1000',
        category: 'headset',
        priceOnline: 'S/ 129.00',
        priceNormal: '̶S̶/̶ ̶1̶3̶9̶.̶0̶0̶',
        img: 'img/Productos/S1000.jpeg',
    },
    {
        id: 8,
        title: 'SmartWatch i9 Pro Max S',
        category: 'smartwatch',
        priceOnline: 'S/ 85.00',
        priceNormal: '̶S̶/̶ ̶9̶9̶.̶0̶0̶',
        img: 'img/Productos/SmartWatch-i9-ProMaxS.jpeg',
    },
    {
        id: 9,
        title: 'SmartWatch T900 Ultra Big 2.09',
        category: 'smartwatch',
        priceOnline: 'S/ 95.00',
        priceNormal: '̶S̶/̶ ̶1̶0̶9̶.̶0̶0̶',
        img: 'img/Productos/SmartWatch-T900-UltraBig-209.jpeg',
    },
];

export default menu;